### ISSUE TITLE
Error: Cannot split window

### ISSUE THREAD

**Issue by obsoleszenz** [MeirKriheli/rusmux#10]
When I'm trying to open this project yaml, rusmux exits with: "Starting project /home/xxx/djsetup/tmuxinator.yml
no space for new pane
Error: Cannot split window djsetup:0
"

Project.yml
```
project_name: djsetup
root: .

windows:
  - main:
      layout: tiled
      # Synchronize all panes of this window, can be enabled before or after the pane commands run.
      # 'before' represents legacy functionality and will be deprecated in a future release, in favour of 'after'
      # synchronize: after
      panes:
        - RUST_LOG=debug serial2midi midify --name Mixer --match "sysex_family == 0x0200"
        - RUST_LOG=debug serial2midi midify --name 4x4 --match "sysex_family == 0x0100"
        - GDK_BACKEND=x11 jalv.gtk https://distrho.kx.studio/plugins/cardinal#fx   -l delay.state -n "Delay"
        - GDK_BACKEND=x11 jalv.gtk https://github.com/michaelwillis/dragonfly-reverb -l reverb.state/ -n "Reverb"
        # - carla ./carla.carxp
        - cd ~/Coding/librecdj && kitty cargo run --bin librecdj --release
        - PIPEWIRE_RATE=1/96000 equis
        - qpwgraph -a $(pwd)/patchbay.qpwgraph
        - pw-top
        - cd ~/Musik/Techno/Sets && echo 'Run equis-record to record :)'
 ```
