### ISSUE TITLE
Window specific root directories

### ISSUE THREAD

**Issue by pgoodjohn** [MeirKriheli/rusmux#16]
Hi

Is `rusmux` supposed to support [window specific root directories](https://github.com/tmuxinator/tmuxinator?tab=readme-ov-file#window-specific-root) from `tmuxinator` configuration files? 

I have been trying to port some of my old setups but I have struggled to make it work:

```yaml
project_name: wip
project_root: ~/Source/
windows:
  - test:
      root: ~/Source/wip/ # <- window specific root
      layout: main-vertical
      panes:
        - echo $(pwd) # <- should print ~/Source/wip/ but prints ~/Source/
~                                          
```

does not set the root directory of the ` app`  window to `~/Source/app/` but it just inherits the parent `project_root`.

Happy to submit a MR sometime soon (™) if supports needs to be added / patched 😄
